class Language {
  final String value;
  final String label;
  final String flag;

  const Language({
    required this.value,
    required this.label,
    required this.flag,
  });

  static const List<Language> allLanguages = [
    Language(value: "en", label: "English", flag: "🇺🇸"),
    Language(value: "bn", label: "Bengali", flag: "🇧🇩"),
    Language(value: "hi", label: "Hindi", flag: "🇮🇳"),
    Language(value: "ar", label: "Arabic", flag: "🇸🇦"),
    Language(value: "zh", label: "Chinese", flag: "🇨🇳"),
    Language(value: "es", label: "Spanish", flag: "🇪🇸"),
    Language(value: "fr", label: "French", flag: "🇫🇷"),
    Language(value: "de", label: "German", flag: "🇩🇪"),
    Language(value: "it", label: "Italian", flag: "🇮🇹"),
    Language(value: "ja", label: "Japanese", flag: "🇯🇵"),
    Language(value: "ko", label: "Korean", flag: "🇰🇷"),
    Language(value: "pt", label: "Portuguese", flag: "🇵🇹"),
    Language(value: "ru", label: "Russian", flag: "🇷🇺"),
    Language(value: "th", label: "Thai", flag: "🇹🇭"),
    Language(value: "tr", label: "Turkish", flag: "🇹🇷"),
    Language(value: "vi", label: "Vietnamese", flag: "🇻🇳"),
    Language(value: "af", label: "Afghan", flag: "🇦🇫"),
    Language(value: "al", label: "Albanian", flag: "🇦🇱"),
    Language(value: "dz", label: "Algerian", flag: "🇩🇿"),
    Language(value: "ao", label: "Angolan", flag: "🇦🇴"),
    Language(value: "am", label: "Armenian", flag: "🇦🇲"),
    Language(value: "au", label: "Australian", flag: "🇦🇺"),
    Language(value: "at", label: "Austrian", flag: "🇦🇹"),
    Language(value: "az", label: "Azerbaijani", flag: "🇦🇿"),
    Language(value: "bh", label: "Bahraini", flag: "🇧🇭"),
    Language(value: "bd", label: "Bangladeshi", flag: "🇧🇩"),
    Language(value: "by", label: "Belarusian", flag: "🇧🇾"),
    Language(value: "be", label: "Belgian", flag: "🇧🇪"),
    Language(value: "bz", label: "Belizean", flag: "🇧🇿"),
    Language(value: "bj", label: "Beninese", flag: "🇧🇯"),
    Language(value: "bo", label: "Bolivian", flag: "🇧🇴"),
    Language(value: "ba", label: "Bosnian", flag: "🇧🇦"),
    Language(value: "bw", label: "Botswana", flag: "🇧🇼"),
    Language(value: "br", label: "Brazilian", flag: "🇧🇷"),
    Language(value: "bg", label: "Bulgarian", flag: "🇧🇬"),
    Language(value: "bf", label: "Burkina Faso", flag: "🇧🇫"),
    Language(value: "bi", label: "Burundian", flag: "🇧🇮"),
    Language(value: "kh", label: "Cambodian", flag: "🇰🇭"),
    Language(value: "cm", label: "Cameroonian", flag: "🇨🇲"),
    Language(value: "ca", label: "Canadian", flag: "🇨🇦"),
    Language(value: "cv", label: "Cape Verdean", flag: "🇨🇻"),
    Language(value: "cl", label: "Chilean", flag: "🇨🇱"),
    Language(value: "cn", label: "Chinese", flag: "🇨🇳"),
    Language(value: "co", label: "Colombian", flag: "🇨🇴"),
    Language(value: "km", label: "Comorian", flag: "🇰🇲"),
    Language(value: "cg", label: "Congolese", flag: "🇨🇬"),
    Language(
      value: "cd",
      label: "Democratic Republic of the Congo",
      flag: "🇨🇩",
    ),
    Language(value: "cr", label: "Costa Rican", flag: "🇨🇷"),
    Language(value: "ci", label: "Ivorian", flag: "🇨🇮"),
    Language(value: "hr", label: "Croatian", flag: "🇭🇷"),
    Language(value: "cu", label: "Cuban", flag: "🇨🇺"),
    Language(value: "cy", label: "Cypriot", flag: "🇨🇾"),
    Language(value: "cz", label: "Czech", flag: "🇨🇿"),
    Language(value: "dk", label: "Danish", flag: "🇩🇰"),
    Language(value: "dj", label: "Djiboutian", flag: "🇩🇯"),
    Language(value: "dm", label: "Dominican", flag: "🇩🇲"),
    Language(value: "do", label: "Dominican Republic", flag: "🇩🇴"),
    Language(value: "ec", label: "Ecuadorian", flag: "🇪🇨"),
    Language(value: "eg", label: "Egyptian", flag: "🇪🇬"),
    Language(value: "sv", label: "Salvadoran", flag: "🇸🇻"),
    Language(value: "gq", label: "Equatorial Guinean", flag: "🇬🇶"),
    Language(value: "er", label: "Eritrean", flag: "🇪🇷"),
    Language(value: "ee", label: "Estonian", flag: "🇪🇪"),
    Language(value: "et", label: "Ethiopian", flag: "🇪🇹"),
    Language(value: "fj", label: "Fijian", flag: "🇫🇯"),
    Language(value: "fi", label: "Finnish", flag: "🇫🇮"),
    Language(value: "ga", label: "Gabonese", flag: "🇬🇦"),
    Language(value: "gm", label: "Gambian", flag: "🇬🇲"),
    Language(value: "ge", label: "Georgian", flag: "🇬🇪"),
    Language(value: "gh", label: "Ghanaian", flag: "🇬🇭"),
    Language(value: "gr", label: "Greek", flag: "🇬🇷"),
    Language(value: "gt", label: "Guatemalan", flag: "🇬🇹"),
    Language(value: "gn", label: "Guinean", flag: "🇬🇳"),
    Language(value: "gw", label: "Guinea-Bissauan", flag: "🇬🇼"),
    Language(value: "gy", label: "Guyanese", flag: "🇬🇾"),
    Language(value: "ht", label: "Haitian", flag: "🇭🇹"),
    Language(value: "hn", label: "Honduran", flag: "🇭🇳"),
    Language(value: "hk", label: "Hong Kong", flag: "🇭🇰"),
    Language(value: "hu", label: "Hungarian", flag: "🇭🇺"),
    Language(value: "is", label: "Icelandic", flag: "🇮🇸"),
    Language(value: "id", label: "Indonesian", flag: "🇮🇩"),
    Language(value: "ir", label: "Iranian", flag: "🇮🇷"),
    Language(value: "iq", label: "Iraqi", flag: "🇮🇶"),
    Language(value: "ie", label: "Irish", flag: "🇮🇪"),
    Language(value: "il", label: "Israeli", flag: "🇮🇱"),
    Language(value: "jm", label: "Jamaican", flag: "🇯🇲"),
    Language(value: "jo", label: "Jordanian", flag: "🇯🇴"),
    Language(value: "kz", label: "Kazakh", flag: "🇰🇿"),
    Language(value: "ke", label: "Kenyan", flag: "🇰🇪"),
    Language(value: "ki", label: "Kiribati", flag: "🇰🇮"),
    Language(value: "kw", label: "Kuwaiti", flag: "🇰🇼"),
    Language(value: "kg", label: "Kyrgyzstani", flag: "🇰🇬"),
    Language(value: "la", label: "Laotian", flag: "🇱🇦"),
    Language(value: "lv", label: "Latvian", flag: "🇱🇻"),
    Language(value: "lb", label: "Lebanese", flag: "🇱🇧"),
    Language(value: "ls", label: "Lesotho", flag: "🇱🇸"),
    Language(value: "lr", label: "Liberian", flag: "🇱🇷"),
    Language(value: "ly", label: "Libyan", flag: "🇱🇾"),
    Language(value: "lt", label: "Lithuanian", flag: "🇱🇹"),
    Language(value: "lu", label: "Luxembourgish", flag: "🇱🇺"),
    Language(value: "mk", label: "Macedonian", flag: "🇲🇰"),
    Language(value: "mg", label: "Malagasy", flag: "🇲🇬"),
    Language(value: "mw", label: "Malawian", flag: "🇲🇼"),
    Language(value: "my", label: "Malaysian", flag: "🇲🇾"),
    Language(value: "mv", label: "Maldivian", flag: "🇲🇻"),
    Language(value: "ml", label: "Malian", flag: "🇲🇱"),
    Language(value: "mt", label: "Maltese", flag: "🇲🇹"),
    Language(value: "mh", label: "Marshallese", flag: "🇲🇭"),
    Language(value: "mq", label: "Martinican", flag: "🇲🇶"),
    Language(value: "mr", label: "Mauritanian", flag: "🇲🇷"),
    Language(value: "mu", label: "Mauritian", flag: "🇲🇺"),
    Language(value: "mx", label: "Mexican", flag: "🇲🇽"),
    Language(value: "fm", label: "Micronesian", flag: "🇫🇲"),
    Language(value: "md", label: "Moldovan", flag: "🇲🇩"),
    Language(value: "mc", label: "Monacan", flag: "🇲🇨"),
    Language(value: "mn", label: "Mongolian", flag: "🇲🇳"),
    Language(value: "me", label: "Montenegrin", flag: "🇲🇪"),
    Language(value: "ma", label: "Moroccan", flag: "🇲🇦"),
    Language(value: "mz", label: "Mozambican", flag: "🇲🇿"),
    Language(value: "mm", label: "Myanmarese", flag: "🇲🇲"),
    Language(value: "na", label: "Namibian", flag: "🇳🇦"),
    Language(value: "np", label: "Nepalese", flag: "🇳🇵"),
    Language(value: "nl", label: "Dutch", flag: "🇳🇱"),
    Language(value: "nc", label: "New Caledonian", flag: "🇳🇨"),
    Language(value: "nz", label: "New Zealand", flag: "🇳🇿"),
    Language(value: "ni", label: "Nicaraguan", flag: "🇳🇮"),
    Language(value: "ne", label: "Nigerien", flag: "🇳🇬"),
    Language(value: "ng", label: "Nigerian", flag: "🇳🇬"),
    Language(value: "no", label: "Norwegian", flag: "🇳🇴"),
    Language(value: "om", label: "Omani", flag: "🇴🇲"),
    Language(value: "pk", label: "Pakistani", flag: "🇵🇰"),
    Language(value: "pw", label: "Palauan", flag: "🇵🇼"),
    Language(value: "pa", label: "Panamanian", flag: "🇵🇦"),
    Language(value: "pg", label: "Papua New Guinean", flag: "🇵🇬"),
    Language(value: "py", label: "Paraguayan", flag: "🇵🇾"),
    Language(value: "pe", label: "Peruvian", flag: "🇵🇪"),
    Language(value: "ph", label: "Philippine", flag: "🇵🇭"),
    Language(value: "pl", label: "Polish", flag: "🇵🇱"),
    Language(value: "qa", label: "Qatari", flag: "🇶🇦"),
    Language(value: "ro", label: "Romanian", flag: "🇷🇴"),
    Language(value: "rw", label: "Rwandan", flag: "🇷🇼"),
    Language(value: "kn", label: "Saint Kitts and Nevis", flag: "🇰🇳"),
    Language(value: "lc", label: "Saint Lucian", flag: "🇱🇨"),
    Language(
      value: "vc",
      label: "Saint Vincent and the Grenadines",
      flag: "🇻🇨",
    ),
    Language(value: "ws", label: "Samoan", flag: "🇼🇸"),
    Language(value: "sm", label: "San Marinese", flag: "🇸🇲"),
    Language(value: "st", label: "Sao Tome and Principe", flag: "🇸🇹"),
    Language(value: "sn", label: "Senegalese", flag: "🇸🇳"),
    Language(value: "rs", label: "Serbian", flag: "🇷🇸"),
    Language(value: "sc", label: "Seychellois", flag: "🇸🇨"),
    Language(value: "sl", label: "Sierra Leonean", flag: "🇸🇱"),
    Language(value: "sg", label: "Singaporean", flag: "🇸🇬"),
    Language(value: "sk", label: "Slovak", flag: "🇸🇰"),
    Language(value: "si", label: "Slovenian", flag: "🇸🇮"),
    Language(value: "sb", label: "Solomon Islander", flag: "🇸🇧"),
    Language(value: "so", label: "Somali", flag: "🇸🇴"),
    Language(value: "za", label: "South African", flag: "🇿🇦"),
    Language(value: "kr", label: "South Korean", flag: "🇰🇷"),
    Language(value: "lk", label: "Sri Lankan", flag: "🇱🇰"),
    Language(value: "sd", label: "Sudanese", flag: "🇸🇩"),
    Language(value: "sr", label: "Surinamese", flag: "🇸🇷"),
    Language(value: "se", label: "Swedish", flag: "🇸🇪"),
    Language(value: "ch", label: "Swiss", flag: "🇨🇭"),
    Language(value: "sy", label: "Syrian", flag: "🇸🇾"),
    Language(value: "tj", label: "Tajikistani", flag: "🇹🇯"),
    Language(value: "tg", label: "Togolese", flag: "🇹🇬"),
    Language(value: "tm", label: "Turkmen", flag: "🇹🇲"),
    Language(value: "tt", label: "Trinidadian", flag: "🇹🇹"),
    Language(value: "tn", label: "Tunisian", flag: "🇹🇳"),
    Language(value: "tz", label: "Tanzanian", flag: "🇹🇿"),
    Language(value: "ua", label: "Ukrainian", flag: "🇺🇦"),
    Language(value: "ug", label: "Ugandan", flag: "🇺🇬"),
    Language(value: "ae", label: "Emirati", flag: "🇦🇪"),
    Language(value: "gb", label: "British", flag: "🇬🇧"),
    Language(value: "us", label: "American", flag: "🇺🇸"),
    Language(value: "uy", label: "Uruguayan", flag: "🇺🇾"),
    Language(value: "uz", label: "Uzbek", flag: "🇺🇿"),
    Language(value: "ve", label: "Venezuelan", flag: "🇻🇪"),
    Language(value: "ye", label: "Yemeni", flag: "🇾🇪"),
    Language(value: "zm", label: "Zambian", flag: "🇿🇲"),
    Language(value: "zw", label: "Zimbabwean", flag: "🇿🇼"),
  ];
}
